[package]
name = "mint"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.3"
solana-program = "1.10.26"

[dev-dependencies]
solana-program-test = "1.10.26"
solana-sdk = "1.10.26"

[lib]
crate-type = ["cdylib", "lib"]